### ISSUE TITLE
Global Navigation Select Menu Behavior 

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/uds-engine#4]
### Feature request

Currently the navigation allows for both the context dropdown and user profile select menu to be open at the same time. Resulting in them being stacked on top of one another. Both should not be open at the same time. When one opens the other should close.

### Describe the solution you'd like

- **Given** The context select menu is open
- **When** a user clicks on the profile menu
- **Then** The context select menu should close, and the user menu should open. 

And vice versa

### Additional context

<img width="604" alt="Screenshot 2024-05-22 at 9 21 07 AM" src="https://github.com/defenseunicorns/uds-engine/assets/92826525/d792ff8c-bca9-4db8-aeb6-98cb34d9b457">

**Comment by BillyFigueroa** [comment]
Video of Navigation working as expected locally

https://github.com/defenseunicorns/uds-engine/assets/1371105/19976ae1-51cb-4fe4-83da-2e76e0046944

**Comment by Madeline-UX** [comment]
Perfect! this meets the expected behavior @BillyFigueroa - Approved lol
